xn-520: add support for updating contacts
teamexos/hubspot-api-go pull request #2
Opened 2020-09-08 18:20 UTC by LeoUrzua

2020-09-08 18:25 UTC, LeoUrzua commented on hubspot/client.go
> +		fmt.Sprintf("%s/crm/%s/objects/contacts/%s?hapikey=%s", c.APIBaseURL, c.APIVersion, requestBody.Properties, c.APIKey),
This line contains an error. I wasn't sure how to take the requestBody.Properties.exos_perform_verified 

I manually added this property in hubspot -> 
![image](https://user-images.githubusercontent.com/23623792/92513906-aa427980-f1d6-11ea-9190-ef532a34b0fd.png)

How can I take this prop?

2020-09-08 18:36 UTC, karhidle commented on hubspot/client.go
> +		fmt.Sprintf("%s/crm/%s/objects/contacts/%s?hapikey=%s", c.APIBaseURL, c.APIVersion, requestBody.Properties, c.APIKey),
@LeoUrzua the properties map is dynamic, as long as you have the property defined in hubspot, then it should accept it. Let's talk in slack.
Regarding the property, I would name it exos_perform_account_verified instead.

2020-09-08 19:13 UTC, LeoUrzua commented on hubspot/client.go
> +		fmt.Sprintf("%s/crm/%s/objects/contacts/%s?hapikey=%s", c.APIBaseURL, c.APIVersion, requestBody.Properties, c.APIKey),
I git commit --amend your suggestions, thanks for your help

2020-09-08 19:15 UTC, karhidle commented on hubspot/client.go
> +		log.Printf("ERROR: unable to update hubspot contact")
```suggestion
		log.Printf("ERROR: unable to update HubSpot contact")
```

2020-09-08 19:16 UTC, karhidle commented on hubspot/client.go
> +	if r.StatusCode != http.StatusCreated {
do they return 201 for this one too?

2020-09-08 19:26 UTC, LeoUrzua commented on hubspot/client.go
> +	if r.StatusCode != http.StatusCreated {
Good catch. updated!

2020-09-08 21:40 UTC, karhidle commented on hubspot/client_test.go
> +			name: "contactAlreadyExists",
Hm I don't think this case is valid for update contact? copy paste issue?

2020-09-08 21:49 UTC, cliffom requested changes

2020-09-08 21:49 UTC, cliffom commented on hubspot/client.go
> +		log.Printf("ERROR: unable to create hubSpot contact")
```suggestion
		log.Printf("ERROR: unable to create HubSpot contact")
```

2020-09-08 21:49 UTC, cliffom commented on hubspot/client.go
> +	//contactInput.Properties.
With proper variable names the code becomes self-documenting and comments like this are not required.
```suggestion
```

2020-09-08 21:49 UTC, cliffom commented on hubspot/client.go
> +		log.Printf("ERROR: unable to update hubSpot contact")
```suggestion
		log.Printf("ERROR: unable to update HubSpot contact")
```

2020-09-08 21:49 UTC, cliffom commented on hubspot/client.go
> +		}
```suggestion
		msg := "ERROR: unable to update HubSpot account:"
		if err != nil {
			log.Printf("%s unable to unmarshal error response.", msg)
		} else {
			log.Printf("%s got error: %v.", msg, errorResponse.Message)
		}
```

2020-09-09 15:53 UTC, cliffom requested changes

2020-09-09 15:53 UTC, cliffom commented on hubspot/client_test.go
> +			name: "contactAlreadyExists",
@LeoUrzua yea, technically the base requirement for an update operation is that the contact already exists.

2020-09-09 15:53 UTC, cliffom commented on hubspot/client.go
> +		requestBody)
I'd prefer to use a single-use variable here as it will make the function call much easier to read.

```suggestion
	}
	
	apiURL := fmt.Sprintf("%s/crm/%s/objects/contacts/%s?hapikey=%s", c.APIBaseURL, c.APIVersion, contactID, c.APIKey)
	r, err := c.request(apiURL, http.MethodPatch, requestBody)
```

2020-09-09 16:06 UTC, karhidle commented on hubspot/client_test.go
> +			name: "badRequest",
you should keep contactAlreadyExists error case from CreateContact, it was only for UpdateContact that it didn't make sense

2020-09-09 18:03 UTC, karhidle approved these changes

2020-09-09 18:04 UTC, cliffom approved these changes

2020-09-09 18:07 UTC, merged