Adds interface to the functions
teamexos/hubspot-api-go pull request #3
Opened 2020-09-29 19:51 UTC by belie

Adds an interface to make testing the functions easier.

2020-09-29 20:03 UTC, karhidle approved these changes

2020-09-30 16:43 UTC, karhidle requested changes
@belie please check this note.
https://github.com/teamexos/perform-services/pull/5#discussion_r497438232

2020-09-30 17:52 UTC, ofalei approved these changes

2020-09-30 17:53 UTC, karhidle approved these changes

2020-09-30 19:20 UTC, merged